describe('database studio', () => {
  beforeEach(() => {
    cy.visit('/?scenario=database')
  })

  it('enables Connect for postgres access and opens the SQL studio', () => {
    cy.get('[data-testid="database-harness"]').should('be.visible')
    cy.contains('PostgreSQL · wms').should('be.visible')
    cy.get('[data-testid="connect-button"]').should('not.be.disabled')
    cy.get('[data-testid="connect-button"]').click()
    cy.get('[data-testid="database-studio"]').should('be.visible')
    cy.contains('orders').should('be.visible')
    cy.get('[data-testid="studio-tab-query-1"]').should('be.visible')
    cy.get('[data-testid="schema-table-orders"]').click()
    cy.get('[data-testid="studio-tab-orders"]').should('be.visible')
    cy.get('[data-testid="table-filter-bar"]').should('be.visible')
    cy.get('[data-testid="query-result-grid"]').should('be.visible')
    cy.get('[data-testid="studio-result-status"]').should('be.visible').and('contain', '2')
    cy.contains('sku').should('be.visible')
    cy.get('[data-testid="session-identity-bar"]').should('be.visible')
    // Row selection lives on the gutter cell; other cells start a cell selection.
    cy.get('[data-testid="grid-row-0"] td').first().click()
    cy.get('[data-testid="grid-row-0"]').should('have.attr', 'data-selected', 'true')
    cy.get('[data-testid="view-mode-record"]').click()
    cy.get('[data-testid="query-result-record"]').should('be.visible')
    cy.get('[data-testid="record-position"]').should('contain', '1')
    cy.get('[data-testid="view-mode-grid"]').click()
    cy.get('[data-testid="studio-new-query"]').click()
    cy.get('[data-testid="studio-tab-query-2"]').should('be.visible')
  })
})
